const TeamKey = {
    "Los Angeles Angels" : {short : "LAA", key : 108},
    "Arizona Diamondbacks" : {short : "ARI", key : 109},
    "Baltimore Orioles" : {short : "BAL", key : 110},
    "Boston Red Sox" : {short : "BOS", key : 111},
    "Chicago Cubs" : {short : "CHC", key : 112},
    "Cincinnati Reds" : {short : "CIN", key : 113},
    "Cleveland Guardians" : {short : "CLE", key : 114},
    "Colorado Rockies" : {short : "COL", key : 115},
    "Detroit Tigers" : {short : "DET", key : 116},
    "Houston Astros" : {short : "HOU", key : 117},
    "Kansas City Royals" : {short : "KC", key : 118},
    "Los Angeles Dodgers" : {short : "LAD", key : 119},
    "Washington Nationals" : {short : "WSH", key : 120},
    "New York Mets" : {short : "NYM", key : 121},
    "Oakland Athletics" : {short : "OAK", key : 133},
    "Pittsburgh Pirates" : {short : "PIT", key : 134},
    "San Diego Padres" : {short : "SD", key : 135},
    "Seattle Mariners" : {short : "SEA", key : 136},
    "San Francisco Giants" : {short : "SF", key : 137},
    "St. Louis Cardinals" : {short : "STL", key : 138},
    "Tampa Bay Rays" : {short : "TB", key : 139},
    "Texas Rangers" : {short : "TEX", key : 140},
    "Toronto Blue Jays" : {short : "TOR", key : 141},
    "Minnesota Twins" : {short : "MIN", key : 142},
    "Philadelphia Phillies" : {short : "PHI", key : 143},
    "Atlanta Braves" : {short : "ATL", key : 144},
    "Chicago White Sox" : {short : "CWS", key : 145},
    "Miami Marlins" : {short : "MIA", key : 146},
    "New York Yankees" : {short : "NYY", key : 147},
    "Milwaukee Brewers" : {short : "MIL", key : 148}
}

export default TeamKey