const TeamKey = {
    "Los Angeles Angels" : {short : "LAA", key : 108, small : "angels", playname : "angels"},
    "Arizona Diamondbacks" : {short : "AZ", key : 109, small : "dbacks", playname : "d-backs"},
    "Baltimore Orioles" : {short : "BAL", key : 110, small : "orioles", playname : "orioles"},
    "Boston Red Sox" : {short : "BOS", key : 111, small : "redsox", playname : "red-sox"},
    "Chicago Cubs" : {short : "CHC", key : 112, small : "cubs", playname : "cubs"},
    "Cincinnati Reds" : {short : "CIN", key : 113, small : "reds", playname : "reds"},
    "Cleveland Guardians" : {short : "CLE", key : 114, small : "guardians", playname : "guardians"},
    "Colorado Rockies" : {short : "COL", key : 115, small : "rockies", playname : "rockies"},
    "Detroit Tigers" : {short : "DET", key : 116, small : "tigers", playname : "tigers"},
    "Houston Astros" : {short : "HOU", key : 117, small : "astros", playname : "astros"},
    "Kansas City Royals" : {short : "KC", key : 118, small : "royals", playname : "royals"},
    "Los Angeles Dodgers" : {short : "LAD", key : 119, small : "dodgers", playname : "dodgers"},
    "Washington Nationals" : {short : "WSH", key : 120, small : "nationals", playname : "nationals"},
    "New York Mets" : {short : "NYM", key : 121, small : "mets", playname : "mets"},
    "Oakland Athletics" : {short : "OAK", key : 133, small : "athletics", playname : "athletics"},
    "Pittsburgh Pirates" : {short : "PIT", key : 134, small : "pirates", playname : "pirates"},
    "San Diego Padres" : {short : "SD", key : 135, small : "padres", playname : "padres"},
    "Seattle Mariners" : {short : "SEA", key : 136, small : "mariners", playname : "mariners"},
    "San Francisco Giants" : {short : "SF", key : 137, small : "giants", playname : "giants"},
    "St. Louis Cardinals" : {short : "STL", key : 138, small : "cardinals", playname : "cardinals"},
    "Tampa Bay Rays" : {short : "TB", key : 139, small : "rays", playname : "rays"},
    "Texas Rangers" : {short : "TEX", key : 140, small : "rangers", playname : "rangers"},
    "Toronto Blue Jays" : {short : "TOR", key : 141, small : "bluejays", playname : "blue-jays"},
    "Minnesota Twins" : {short : "MIN", key : 142, small : "twins", playname : "twins"},
    "Philadelphia Phillies" : {short : "PHI", key : 143, small : "phillies", playname : "phillies"},
    "Atlanta Braves" : {short : "ATL", key : 144, small : "braves", playname : "braves"},
    "Chicago White Sox" : {short : "CWS", key : 145, small : "whitesox", playname : "white-sox"},
    "Miami Marlins" : {short : "MIA", key : 146, small : "marlins", playname : "marlins"},
    "New York Yankees" : {short : "NYY", key : 147, small : "yankees", playname : "yankees"},
    "Milwaukee Brewers" : {short : "MIL", key : 148, small : "brewers", playname : "brewers"}
}

export default TeamKey